apiVersion: apps/v1
kind: Deployment
metadata:
  name: deskly-location
  namespace: deskly
spec:
  selector:
    matchLabels:
      app: deskly-location
  template:
    metadata:
      labels:
        app: deskly-location
    spec:
      containers:
        - name: deskly-location
          image: ${IMAGE_NAME}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: ${SPRING_DATASOURCE_URL}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: deskly-location-secrets-prod
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deskly-location-secrets-prod
                  key: SPRING_DATASOURCE_PASSWORD
            - name: AWS_SQS_URL
              value: ${AWS_SQS_URL}
            - name: AWS_BUCKET_NAME
              value: ${AWS_BUCKET_NAME}
            - name: AWS_DEFAULT_REGION
              value: ${AWS_DEFAULT_REGION}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: deskly-location-secrets-prod
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: deskly-location-secrets-prod
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: deskly-location-secrets-prod
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 720Mi
              cpu: 500m
            limits:
              memory: 720Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: deskly-location
  namespace: deskly
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: deskly-location
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deskly-location
  namespace: deskly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deskly-location
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90  