# H2 DEV config
spring:
  h2:
    console:
      enabled: true
      path: /api/v1/deskly-core/h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema-availability.sql

aws:
  sqs:
    url: ${AWS_SQS_URL}
  region: ${AWS_DEFAULT_REGION}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  session-token: ${AWS_SESSION_TOKEN}
