# PostgreSQL PROD config
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema-availability.sql

aws:
  sqs:
    url: ${AWS_SQS_URL}
  region: ${AWS_DEFAULT_REGION}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  session-token: ${AWS_SESSION_TOKEN}